#!/bin/sh
pngloss -fv -s1 -o compressed/barbara-s01.png barbara.png
pngloss -fv -s2 -o compressed/barbara-s02.png barbara.png
pngloss -fv -s3 -o compressed/barbara-s03.png barbara.png
pngloss -fv -s4 -o compressed/barbara-s04.png barbara.png
pngloss -fv -s5 -o compressed/barbara-s05.png barbara.png
pngloss -fv -s6 -o compressed/barbara-s06.png barbara.png
pngloss -fv -s7 -o compressed/barbara-s07.png barbara.png
pngloss -fv -s8 -o compressed/barbara-s08.png barbara.png
pngloss -fv -s9 -o compressed/barbara-s09.png barbara.png
pngloss -fv -s10 -o compressed/barbara-s10.png barbara.png
pngloss -fv -s11 -o compressed/barbara-s11.png barbara.png
pngloss -fv -s12 -o compressed/barbara-s12.png barbara.png
pngloss -fv -s13 -o compressed/barbara-s13.png barbara.png
pngloss -fv -s14 -o compressed/barbara-s14.png barbara.png
pngloss -fv -s15 -o compressed/barbara-s15.png barbara.png
pngloss -fv -s16 -o compressed/barbara-s16.png barbara.png
pngloss -fv -s17 -o compressed/barbara-s17.png barbara.png
pngloss -fv -s18 -o compressed/barbara-s18.png barbara.png
pngloss -fv -s19 -o compressed/barbara-s19.png barbara.png
pngloss -fv -s20 -o compressed/barbara-s20.png barbara.png
pngloss -fv -s21 -o compressed/barbara-s21.png barbara.png
pngloss -fv -s22 -o compressed/barbara-s22.png barbara.png
pngloss -fv -s23 -o compressed/barbara-s23.png barbara.png
pngloss -fv -s24 -o compressed/barbara-s24.png barbara.png
pngloss -fv -s25 -o compressed/barbara-s25.png barbara.png
pngloss -fv -s26 -o compressed/barbara-s26.png barbara.png
pngloss -fv -s27 -o compressed/barbara-s27.png barbara.png
pngloss -fv -s28 -o compressed/barbara-s28.png barbara.png
pngloss -fv -s29 -o compressed/barbara-s29.png barbara.png
pngloss -fv -s30 -o compressed/barbara-s30.png barbara.png
pngloss -fv -s31 -o compressed/barbara-s31.png barbara.png
pngloss -fv -s32 -o compressed/barbara-s32.png barbara.png
pngloss -fv -s33 -o compressed/barbara-s33.png barbara.png
pngloss -fv -s34 -o compressed/barbara-s34.png barbara.png
pngloss -fv -s35 -o compressed/barbara-s35.png barbara.png
pngloss -fv -s36 -o compressed/barbara-s36.png barbara.png
pngloss -fv -s37 -o compressed/barbara-s37.png barbara.png
pngloss -fv -s38 -o compressed/barbara-s38.png barbara.png
pngloss -fv -s39 -o compressed/barbara-s39.png barbara.png
pngloss -fv -s40 -o compressed/barbara-s40.png barbara.png
pngloss -fv -s41 -o compressed/barbara-s41.png barbara.png
pngloss -fv -s42 -o compressed/barbara-s42.png barbara.png
pngloss -fv -s43 -o compressed/barbara-s43.png barbara.png
pngloss -fv -s44 -o compressed/barbara-s44.png barbara.png
pngloss -fv -s45 -o compressed/barbara-s45.png barbara.png
pngloss -fv -s46 -o compressed/barbara-s46.png barbara.png
pngloss -fv -s47 -o compressed/barbara-s47.png barbara.png
pngloss -fv -s48 -o compressed/barbara-s48.png barbara.png
pngloss -fv -s49 -o compressed/barbara-s49.png barbara.png
pngloss -fv -s50 -o compressed/barbara-s50.png barbara.png
pngloss -fv -s51 -o compressed/barbara-s51.png barbara.png
pngloss -fv -s52 -o compressed/barbara-s52.png barbara.png
pngloss -fv -s53 -o compressed/barbara-s53.png barbara.png
pngloss -fv -s54 -o compressed/barbara-s54.png barbara.png
pngloss -fv -s55 -o compressed/barbara-s55.png barbara.png
pngloss -fv -s56 -o compressed/barbara-s56.png barbara.png
pngloss -fv -s57 -o compressed/barbara-s57.png barbara.png
pngloss -fv -s58 -o compressed/barbara-s58.png barbara.png
pngloss -fv -s59 -o compressed/barbara-s59.png barbara.png
pngloss -fv -s60 -o compressed/barbara-s60.png barbara.png
pngloss -fv -s61 -o compressed/barbara-s61.png barbara.png
pngloss -fv -s62 -o compressed/barbara-s62.png barbara.png
pngloss -fv -s63 -o compressed/barbara-s63.png barbara.png
pngloss -fv -s64 -o compressed/barbara-s64.png barbara.png
pngloss -fv -s65 -o compressed/barbara-s65.png barbara.png
pngloss -fv -s66 -o compressed/barbara-s66.png barbara.png
pngloss -fv -s67 -o compressed/barbara-s67.png barbara.png
pngloss -fv -s68 -o compressed/barbara-s68.png barbara.png
pngloss -fv -s69 -o compressed/barbara-s69.png barbara.png
pngloss -fv -s70 -o compressed/barbara-s70.png barbara.png
pngloss -fv -s71 -o compressed/barbara-s71.png barbara.png
pngloss -fv -s72 -o compressed/barbara-s72.png barbara.png
pngloss -fv -s73 -o compressed/barbara-s73.png barbara.png
pngloss -fv -s74 -o compressed/barbara-s74.png barbara.png
pngloss -fv -s75 -o compressed/barbara-s75.png barbara.png
pngloss -fv -s76 -o compressed/barbara-s76.png barbara.png
pngloss -fv -s77 -o compressed/barbara-s77.png barbara.png
pngloss -fv -s78 -o compressed/barbara-s78.png barbara.png
pngloss -fv -s79 -o compressed/barbara-s79.png barbara.png
pngloss -fv -s80 -o compressed/barbara-s80.png barbara.png
pngloss -fv -s81 -o compressed/barbara-s81.png barbara.png
pngloss -fv -s82 -o compressed/barbara-s82.png barbara.png
pngloss -fv -s83 -o compressed/barbara-s83.png barbara.png
pngloss -fv -s84 -o compressed/barbara-s84.png barbara.png
pngloss -fv -s85 -o compressed/barbara-s85.png barbara.png
pngloss -fv -s86 -o compressed/barbara-s86.png barbara.png
pngloss -fv -s87 -o compressed/barbara-s87.png barbara.png
pngloss -fv -s88 -o compressed/barbara-s88.png barbara.png
pngloss -fv -s89 -o compressed/barbara-s89.png barbara.png
pngloss -fv -s90 -o compressed/barbara-s90.png barbara.png
pngloss -fv -s91 -o compressed/barbara-s91.png barbara.png
pngloss -fv -s92 -o compressed/barbara-s92.png barbara.png
pngloss -fv -s93 -o compressed/barbara-s93.png barbara.png
pngloss -fv -s94 -o compressed/barbara-s94.png barbara.png
pngloss -fv -s95 -o compressed/barbara-s95.png barbara.png
pngloss -fv -s96 -o compressed/barbara-s96.png barbara.png
pngloss -fv -s97 -o compressed/barbara-s97.png barbara.png
pngloss -fv -s98 -o compressed/barbara-s98.png barbara.png
pngloss -fv -s99 -o compressed/barbara-s99.png barbara.png
pngloss -fv -s1 -o compressed/david-s01.png david.png
pngloss -fv -s2 -o compressed/david-s02.png david.png
pngloss -fv -s3 -o compressed/david-s03.png david.png
pngloss -fv -s4 -o compressed/david-s04.png david.png
pngloss -fv -s5 -o compressed/david-s05.png david.png
pngloss -fv -s6 -o compressed/david-s06.png david.png
pngloss -fv -s7 -o compressed/david-s07.png david.png
pngloss -fv -s8 -o compressed/david-s08.png david.png
pngloss -fv -s9 -o compressed/david-s09.png david.png
pngloss -fv -s10 -o compressed/david-s10.png david.png
pngloss -fv -s11 -o compressed/david-s11.png david.png
pngloss -fv -s12 -o compressed/david-s12.png david.png
pngloss -fv -s13 -o compressed/david-s13.png david.png
pngloss -fv -s14 -o compressed/david-s14.png david.png
pngloss -fv -s15 -o compressed/david-s15.png david.png
pngloss -fv -s16 -o compressed/david-s16.png david.png
pngloss -fv -s17 -o compressed/david-s17.png david.png
pngloss -fv -s18 -o compressed/david-s18.png david.png
pngloss -fv -s19 -o compressed/david-s19.png david.png
pngloss -fv -s20 -o compressed/david-s20.png david.png
pngloss -fv -s21 -o compressed/david-s21.png david.png
pngloss -fv -s22 -o compressed/david-s22.png david.png
pngloss -fv -s23 -o compressed/david-s23.png david.png
pngloss -fv -s24 -o compressed/david-s24.png david.png
pngloss -fv -s25 -o compressed/david-s25.png david.png
pngloss -fv -s26 -o compressed/david-s26.png david.png
pngloss -fv -s27 -o compressed/david-s27.png david.png
pngloss -fv -s28 -o compressed/david-s28.png david.png
pngloss -fv -s29 -o compressed/david-s29.png david.png
pngloss -fv -s30 -o compressed/david-s30.png david.png
pngloss -fv -s31 -o compressed/david-s31.png david.png
pngloss -fv -s32 -o compressed/david-s32.png david.png
pngloss -fv -s33 -o compressed/david-s33.png david.png
pngloss -fv -s34 -o compressed/david-s34.png david.png
pngloss -fv -s35 -o compressed/david-s35.png david.png
pngloss -fv -s36 -o compressed/david-s36.png david.png
pngloss -fv -s37 -o compressed/david-s37.png david.png
pngloss -fv -s38 -o compressed/david-s38.png david.png
pngloss -fv -s39 -o compressed/david-s39.png david.png
pngloss -fv -s40 -o compressed/david-s40.png david.png
pngloss -fv -s41 -o compressed/david-s41.png david.png
pngloss -fv -s42 -o compressed/david-s42.png david.png
pngloss -fv -s43 -o compressed/david-s43.png david.png
pngloss -fv -s44 -o compressed/david-s44.png david.png
pngloss -fv -s45 -o compressed/david-s45.png david.png
pngloss -fv -s46 -o compressed/david-s46.png david.png
pngloss -fv -s47 -o compressed/david-s47.png david.png
pngloss -fv -s48 -o compressed/david-s48.png david.png
pngloss -fv -s49 -o compressed/david-s49.png david.png
pngloss -fv -s50 -o compressed/david-s50.png david.png
pngloss -fv -s51 -o compressed/david-s51.png david.png
pngloss -fv -s52 -o compressed/david-s52.png david.png
pngloss -fv -s53 -o compressed/david-s53.png david.png
pngloss -fv -s54 -o compressed/david-s54.png david.png
pngloss -fv -s55 -o compressed/david-s55.png david.png
pngloss -fv -s56 -o compressed/david-s56.png david.png
pngloss -fv -s57 -o compressed/david-s57.png david.png
pngloss -fv -s58 -o compressed/david-s58.png david.png
pngloss -fv -s59 -o compressed/david-s59.png david.png
pngloss -fv -s60 -o compressed/david-s60.png david.png
pngloss -fv -s61 -o compressed/david-s61.png david.png
pngloss -fv -s62 -o compressed/david-s62.png david.png
pngloss -fv -s63 -o compressed/david-s63.png david.png
pngloss -fv -s64 -o compressed/david-s64.png david.png
pngloss -fv -s65 -o compressed/david-s65.png david.png
pngloss -fv -s66 -o compressed/david-s66.png david.png
pngloss -fv -s67 -o compressed/david-s67.png david.png
pngloss -fv -s68 -o compressed/david-s68.png david.png
pngloss -fv -s69 -o compressed/david-s69.png david.png
pngloss -fv -s70 -o compressed/david-s70.png david.png
pngloss -fv -s71 -o compressed/david-s71.png david.png
pngloss -fv -s72 -o compressed/david-s72.png david.png
pngloss -fv -s73 -o compressed/david-s73.png david.png
pngloss -fv -s74 -o compressed/david-s74.png david.png
pngloss -fv -s75 -o compressed/david-s75.png david.png
pngloss -fv -s76 -o compressed/david-s76.png david.png
pngloss -fv -s77 -o compressed/david-s77.png david.png
pngloss -fv -s78 -o compressed/david-s78.png david.png
pngloss -fv -s79 -o compressed/david-s79.png david.png
pngloss -fv -s80 -o compressed/david-s80.png david.png
pngloss -fv -s81 -o compressed/david-s81.png david.png
pngloss -fv -s82 -o compressed/david-s82.png david.png
pngloss -fv -s83 -o compressed/david-s83.png david.png
pngloss -fv -s84 -o compressed/david-s84.png david.png
pngloss -fv -s85 -o compressed/david-s85.png david.png
pngloss -fv -s86 -o compressed/david-s86.png david.png
pngloss -fv -s87 -o compressed/david-s87.png david.png
pngloss -fv -s88 -o compressed/david-s88.png david.png
pngloss -fv -s89 -o compressed/david-s89.png david.png
pngloss -fv -s90 -o compressed/david-s90.png david.png
pngloss -fv -s91 -o compressed/david-s91.png david.png
pngloss -fv -s92 -o compressed/david-s92.png david.png
pngloss -fv -s93 -o compressed/david-s93.png david.png
pngloss -fv -s94 -o compressed/david-s94.png david.png
pngloss -fv -s95 -o compressed/david-s95.png david.png
pngloss -fv -s96 -o compressed/david-s96.png david.png
pngloss -fv -s97 -o compressed/david-s97.png david.png
pngloss -fv -s98 -o compressed/david-s98.png david.png
pngloss -fv -s99 -o compressed/david-s99.png david.png
pngloss -fv -s1 -o compressed/dice-s01.png dice.png
pngloss -fv -s2 -o compressed/dice-s02.png dice.png
pngloss -fv -s3 -o compressed/dice-s03.png dice.png
pngloss -fv -s4 -o compressed/dice-s04.png dice.png
pngloss -fv -s5 -o compressed/dice-s05.png dice.png
pngloss -fv -s6 -o compressed/dice-s06.png dice.png
pngloss -fv -s7 -o compressed/dice-s07.png dice.png
pngloss -fv -s8 -o compressed/dice-s08.png dice.png
pngloss -fv -s9 -o compressed/dice-s09.png dice.png
pngloss -fv -s10 -o compressed/dice-s10.png dice.png
pngloss -fv -s11 -o compressed/dice-s11.png dice.png
pngloss -fv -s12 -o compressed/dice-s12.png dice.png
pngloss -fv -s13 -o compressed/dice-s13.png dice.png
pngloss -fv -s14 -o compressed/dice-s14.png dice.png
pngloss -fv -s15 -o compressed/dice-s15.png dice.png
pngloss -fv -s16 -o compressed/dice-s16.png dice.png
pngloss -fv -s17 -o compressed/dice-s17.png dice.png
pngloss -fv -s18 -o compressed/dice-s18.png dice.png
pngloss -fv -s19 -o compressed/dice-s19.png dice.png
pngloss -fv -s20 -o compressed/dice-s20.png dice.png
pngloss -fv -s21 -o compressed/dice-s21.png dice.png
pngloss -fv -s22 -o compressed/dice-s22.png dice.png
pngloss -fv -s23 -o compressed/dice-s23.png dice.png
pngloss -fv -s24 -o compressed/dice-s24.png dice.png
pngloss -fv -s25 -o compressed/dice-s25.png dice.png
pngloss -fv -s26 -o compressed/dice-s26.png dice.png
pngloss -fv -s27 -o compressed/dice-s27.png dice.png
pngloss -fv -s28 -o compressed/dice-s28.png dice.png
pngloss -fv -s29 -o compressed/dice-s29.png dice.png
pngloss -fv -s30 -o compressed/dice-s30.png dice.png
pngloss -fv -s31 -o compressed/dice-s31.png dice.png
pngloss -fv -s32 -o compressed/dice-s32.png dice.png
pngloss -fv -s33 -o compressed/dice-s33.png dice.png
pngloss -fv -s34 -o compressed/dice-s34.png dice.png
pngloss -fv -s35 -o compressed/dice-s35.png dice.png
pngloss -fv -s36 -o compressed/dice-s36.png dice.png
pngloss -fv -s37 -o compressed/dice-s37.png dice.png
pngloss -fv -s38 -o compressed/dice-s38.png dice.png
pngloss -fv -s39 -o compressed/dice-s39.png dice.png
pngloss -fv -s40 -o compressed/dice-s40.png dice.png
pngloss -fv -s41 -o compressed/dice-s41.png dice.png
pngloss -fv -s42 -o compressed/dice-s42.png dice.png
pngloss -fv -s43 -o compressed/dice-s43.png dice.png
pngloss -fv -s44 -o compressed/dice-s44.png dice.png
pngloss -fv -s45 -o compressed/dice-s45.png dice.png
pngloss -fv -s46 -o compressed/dice-s46.png dice.png
pngloss -fv -s47 -o compressed/dice-s47.png dice.png
pngloss -fv -s48 -o compressed/dice-s48.png dice.png
pngloss -fv -s49 -o compressed/dice-s49.png dice.png
pngloss -fv -s50 -o compressed/dice-s50.png dice.png
pngloss -fv -s51 -o compressed/dice-s51.png dice.png
pngloss -fv -s52 -o compressed/dice-s52.png dice.png
pngloss -fv -s53 -o compressed/dice-s53.png dice.png
pngloss -fv -s54 -o compressed/dice-s54.png dice.png
pngloss -fv -s55 -o compressed/dice-s55.png dice.png
pngloss -fv -s56 -o compressed/dice-s56.png dice.png
pngloss -fv -s57 -o compressed/dice-s57.png dice.png
pngloss -fv -s58 -o compressed/dice-s58.png dice.png
pngloss -fv -s59 -o compressed/dice-s59.png dice.png
pngloss -fv -s60 -o compressed/dice-s60.png dice.png
pngloss -fv -s61 -o compressed/dice-s61.png dice.png
pngloss -fv -s62 -o compressed/dice-s62.png dice.png
pngloss -fv -s63 -o compressed/dice-s63.png dice.png
pngloss -fv -s64 -o compressed/dice-s64.png dice.png
pngloss -fv -s65 -o compressed/dice-s65.png dice.png
pngloss -fv -s66 -o compressed/dice-s66.png dice.png
pngloss -fv -s67 -o compressed/dice-s67.png dice.png
pngloss -fv -s68 -o compressed/dice-s68.png dice.png
pngloss -fv -s69 -o compressed/dice-s69.png dice.png
pngloss -fv -s70 -o compressed/dice-s70.png dice.png
pngloss -fv -s71 -o compressed/dice-s71.png dice.png
pngloss -fv -s72 -o compressed/dice-s72.png dice.png
pngloss -fv -s73 -o compressed/dice-s73.png dice.png
pngloss -fv -s74 -o compressed/dice-s74.png dice.png
pngloss -fv -s75 -o compressed/dice-s75.png dice.png
pngloss -fv -s76 -o compressed/dice-s76.png dice.png
pngloss -fv -s77 -o compressed/dice-s77.png dice.png
pngloss -fv -s78 -o compressed/dice-s78.png dice.png
pngloss -fv -s79 -o compressed/dice-s79.png dice.png
pngloss -fv -s80 -o compressed/dice-s80.png dice.png
pngloss -fv -s81 -o compressed/dice-s81.png dice.png
pngloss -fv -s82 -o compressed/dice-s82.png dice.png
pngloss -fv -s83 -o compressed/dice-s83.png dice.png
pngloss -fv -s84 -o compressed/dice-s84.png dice.png
pngloss -fv -s85 -o compressed/dice-s85.png dice.png
pngloss -fv -s86 -o compressed/dice-s86.png dice.png
pngloss -fv -s87 -o compressed/dice-s87.png dice.png
pngloss -fv -s88 -o compressed/dice-s88.png dice.png
pngloss -fv -s89 -o compressed/dice-s89.png dice.png
pngloss -fv -s90 -o compressed/dice-s90.png dice.png
pngloss -fv -s91 -o compressed/dice-s91.png dice.png
pngloss -fv -s92 -o compressed/dice-s92.png dice.png
pngloss -fv -s93 -o compressed/dice-s93.png dice.png
pngloss -fv -s94 -o compressed/dice-s94.png dice.png
pngloss -fv -s95 -o compressed/dice-s95.png dice.png
pngloss -fv -s96 -o compressed/dice-s96.png dice.png
pngloss -fv -s97 -o compressed/dice-s97.png dice.png
pngloss -fv -s98 -o compressed/dice-s98.png dice.png
pngloss -fv -s99 -o compressed/dice-s99.png dice.png
pngloss -fv -s1 -o compressed/girl-s01.png girl.png
pngloss -fv -s2 -o compressed/girl-s02.png girl.png
pngloss -fv -s3 -o compressed/girl-s03.png girl.png
pngloss -fv -s4 -o compressed/girl-s04.png girl.png
pngloss -fv -s5 -o compressed/girl-s05.png girl.png
pngloss -fv -s6 -o compressed/girl-s06.png girl.png
pngloss -fv -s7 -o compressed/girl-s07.png girl.png
pngloss -fv -s8 -o compressed/girl-s08.png girl.png
pngloss -fv -s9 -o compressed/girl-s09.png girl.png
pngloss -fv -s10 -o compressed/girl-s10.png girl.png
pngloss -fv -s11 -o compressed/girl-s11.png girl.png
pngloss -fv -s12 -o compressed/girl-s12.png girl.png
pngloss -fv -s13 -o compressed/girl-s13.png girl.png
pngloss -fv -s14 -o compressed/girl-s14.png girl.png
pngloss -fv -s15 -o compressed/girl-s15.png girl.png
pngloss -fv -s16 -o compressed/girl-s16.png girl.png
pngloss -fv -s17 -o compressed/girl-s17.png girl.png
pngloss -fv -s18 -o compressed/girl-s18.png girl.png
pngloss -fv -s19 -o compressed/girl-s19.png girl.png
pngloss -fv -s20 -o compressed/girl-s20.png girl.png
pngloss -fv -s21 -o compressed/girl-s21.png girl.png
pngloss -fv -s22 -o compressed/girl-s22.png girl.png
pngloss -fv -s23 -o compressed/girl-s23.png girl.png
pngloss -fv -s24 -o compressed/girl-s24.png girl.png
pngloss -fv -s25 -o compressed/girl-s25.png girl.png
pngloss -fv -s26 -o compressed/girl-s26.png girl.png
pngloss -fv -s27 -o compressed/girl-s27.png girl.png
pngloss -fv -s28 -o compressed/girl-s28.png girl.png
pngloss -fv -s29 -o compressed/girl-s29.png girl.png
pngloss -fv -s30 -o compressed/girl-s30.png girl.png
pngloss -fv -s31 -o compressed/girl-s31.png girl.png
pngloss -fv -s32 -o compressed/girl-s32.png girl.png
pngloss -fv -s33 -o compressed/girl-s33.png girl.png
pngloss -fv -s34 -o compressed/girl-s34.png girl.png
pngloss -fv -s35 -o compressed/girl-s35.png girl.png
pngloss -fv -s36 -o compressed/girl-s36.png girl.png
pngloss -fv -s37 -o compressed/girl-s37.png girl.png
pngloss -fv -s38 -o compressed/girl-s38.png girl.png
pngloss -fv -s39 -o compressed/girl-s39.png girl.png
pngloss -fv -s40 -o compressed/girl-s40.png girl.png
pngloss -fv -s41 -o compressed/girl-s41.png girl.png
pngloss -fv -s42 -o compressed/girl-s42.png girl.png
pngloss -fv -s43 -o compressed/girl-s43.png girl.png
pngloss -fv -s44 -o compressed/girl-s44.png girl.png
pngloss -fv -s45 -o compressed/girl-s45.png girl.png
pngloss -fv -s46 -o compressed/girl-s46.png girl.png
pngloss -fv -s47 -o compressed/girl-s47.png girl.png
pngloss -fv -s48 -o compressed/girl-s48.png girl.png
pngloss -fv -s49 -o compressed/girl-s49.png girl.png
pngloss -fv -s50 -o compressed/girl-s50.png girl.png
pngloss -fv -s51 -o compressed/girl-s51.png girl.png
pngloss -fv -s52 -o compressed/girl-s52.png girl.png
pngloss -fv -s53 -o compressed/girl-s53.png girl.png
pngloss -fv -s54 -o compressed/girl-s54.png girl.png
pngloss -fv -s55 -o compressed/girl-s55.png girl.png
pngloss -fv -s56 -o compressed/girl-s56.png girl.png
pngloss -fv -s57 -o compressed/girl-s57.png girl.png
pngloss -fv -s58 -o compressed/girl-s58.png girl.png
pngloss -fv -s59 -o compressed/girl-s59.png girl.png
pngloss -fv -s60 -o compressed/girl-s60.png girl.png
pngloss -fv -s61 -o compressed/girl-s61.png girl.png
pngloss -fv -s62 -o compressed/girl-s62.png girl.png
pngloss -fv -s63 -o compressed/girl-s63.png girl.png
pngloss -fv -s64 -o compressed/girl-s64.png girl.png
pngloss -fv -s65 -o compressed/girl-s65.png girl.png
pngloss -fv -s66 -o compressed/girl-s66.png girl.png
pngloss -fv -s67 -o compressed/girl-s67.png girl.png
pngloss -fv -s68 -o compressed/girl-s68.png girl.png
pngloss -fv -s69 -o compressed/girl-s69.png girl.png
pngloss -fv -s70 -o compressed/girl-s70.png girl.png
pngloss -fv -s71 -o compressed/girl-s71.png girl.png
pngloss -fv -s72 -o compressed/girl-s72.png girl.png
pngloss -fv -s73 -o compressed/girl-s73.png girl.png
pngloss -fv -s74 -o compressed/girl-s74.png girl.png
pngloss -fv -s75 -o compressed/girl-s75.png girl.png
pngloss -fv -s76 -o compressed/girl-s76.png girl.png
pngloss -fv -s77 -o compressed/girl-s77.png girl.png
pngloss -fv -s78 -o compressed/girl-s78.png girl.png
pngloss -fv -s79 -o compressed/girl-s79.png girl.png
pngloss -fv -s80 -o compressed/girl-s80.png girl.png
pngloss -fv -s81 -o compressed/girl-s81.png girl.png
pngloss -fv -s82 -o compressed/girl-s82.png girl.png
pngloss -fv -s83 -o compressed/girl-s83.png girl.png
pngloss -fv -s84 -o compressed/girl-s84.png girl.png
pngloss -fv -s85 -o compressed/girl-s85.png girl.png
pngloss -fv -s86 -o compressed/girl-s86.png girl.png
pngloss -fv -s87 -o compressed/girl-s87.png girl.png
pngloss -fv -s88 -o compressed/girl-s88.png girl.png
pngloss -fv -s89 -o compressed/girl-s89.png girl.png
pngloss -fv -s90 -o compressed/girl-s90.png girl.png
pngloss -fv -s91 -o compressed/girl-s91.png girl.png
pngloss -fv -s92 -o compressed/girl-s92.png girl.png
pngloss -fv -s93 -o compressed/girl-s93.png girl.png
pngloss -fv -s94 -o compressed/girl-s94.png girl.png
pngloss -fv -s95 -o compressed/girl-s95.png girl.png
pngloss -fv -s96 -o compressed/girl-s96.png girl.png
pngloss -fv -s97 -o compressed/girl-s97.png girl.png
pngloss -fv -s98 -o compressed/girl-s98.png girl.png
pngloss -fv -s99 -o compressed/girl-s99.png girl.png
pngloss -fv -s1 -o compressed/lena-s01.png lena.png
pngloss -fv -s2 -o compressed/lena-s02.png lena.png
pngloss -fv -s3 -o compressed/lena-s03.png lena.png
pngloss -fv -s4 -o compressed/lena-s04.png lena.png
pngloss -fv -s5 -o compressed/lena-s05.png lena.png
pngloss -fv -s6 -o compressed/lena-s06.png lena.png
pngloss -fv -s7 -o compressed/lena-s07.png lena.png
pngloss -fv -s8 -o compressed/lena-s08.png lena.png
pngloss -fv -s9 -o compressed/lena-s09.png lena.png
pngloss -fv -s10 -o compressed/lena-s10.png lena.png
pngloss -fv -s11 -o compressed/lena-s11.png lena.png
pngloss -fv -s12 -o compressed/lena-s12.png lena.png
pngloss -fv -s13 -o compressed/lena-s13.png lena.png
pngloss -fv -s14 -o compressed/lena-s14.png lena.png
pngloss -fv -s15 -o compressed/lena-s15.png lena.png
pngloss -fv -s16 -o compressed/lena-s16.png lena.png
pngloss -fv -s17 -o compressed/lena-s17.png lena.png
pngloss -fv -s18 -o compressed/lena-s18.png lena.png
pngloss -fv -s19 -o compressed/lena-s19.png lena.png
pngloss -fv -s20 -o compressed/lena-s20.png lena.png
pngloss -fv -s21 -o compressed/lena-s21.png lena.png
pngloss -fv -s22 -o compressed/lena-s22.png lena.png
pngloss -fv -s23 -o compressed/lena-s23.png lena.png
pngloss -fv -s24 -o compressed/lena-s24.png lena.png
pngloss -fv -s25 -o compressed/lena-s25.png lena.png
pngloss -fv -s26 -o compressed/lena-s26.png lena.png
pngloss -fv -s27 -o compressed/lena-s27.png lena.png
pngloss -fv -s28 -o compressed/lena-s28.png lena.png
pngloss -fv -s29 -o compressed/lena-s29.png lena.png
pngloss -fv -s30 -o compressed/lena-s30.png lena.png
pngloss -fv -s31 -o compressed/lena-s31.png lena.png
pngloss -fv -s32 -o compressed/lena-s32.png lena.png
pngloss -fv -s33 -o compressed/lena-s33.png lena.png
pngloss -fv -s34 -o compressed/lena-s34.png lena.png
pngloss -fv -s35 -o compressed/lena-s35.png lena.png
pngloss -fv -s36 -o compressed/lena-s36.png lena.png
pngloss -fv -s37 -o compressed/lena-s37.png lena.png
pngloss -fv -s38 -o compressed/lena-s38.png lena.png
pngloss -fv -s39 -o compressed/lena-s39.png lena.png
pngloss -fv -s40 -o compressed/lena-s40.png lena.png
pngloss -fv -s41 -o compressed/lena-s41.png lena.png
pngloss -fv -s42 -o compressed/lena-s42.png lena.png
pngloss -fv -s43 -o compressed/lena-s43.png lena.png
pngloss -fv -s44 -o compressed/lena-s44.png lena.png
pngloss -fv -s45 -o compressed/lena-s45.png lena.png
pngloss -fv -s46 -o compressed/lena-s46.png lena.png
pngloss -fv -s47 -o compressed/lena-s47.png lena.png
pngloss -fv -s48 -o compressed/lena-s48.png lena.png
pngloss -fv -s49 -o compressed/lena-s49.png lena.png
pngloss -fv -s50 -o compressed/lena-s50.png lena.png
pngloss -fv -s51 -o compressed/lena-s51.png lena.png
pngloss -fv -s52 -o compressed/lena-s52.png lena.png
pngloss -fv -s53 -o compressed/lena-s53.png lena.png
pngloss -fv -s54 -o compressed/lena-s54.png lena.png
pngloss -fv -s55 -o compressed/lena-s55.png lena.png
pngloss -fv -s56 -o compressed/lena-s56.png lena.png
pngloss -fv -s57 -o compressed/lena-s57.png lena.png
pngloss -fv -s58 -o compressed/lena-s58.png lena.png
pngloss -fv -s59 -o compressed/lena-s59.png lena.png
pngloss -fv -s60 -o compressed/lena-s60.png lena.png
pngloss -fv -s61 -o compressed/lena-s61.png lena.png
pngloss -fv -s62 -o compressed/lena-s62.png lena.png
pngloss -fv -s63 -o compressed/lena-s63.png lena.png
pngloss -fv -s64 -o compressed/lena-s64.png lena.png
pngloss -fv -s65 -o compressed/lena-s65.png lena.png
pngloss -fv -s66 -o compressed/lena-s66.png lena.png
pngloss -fv -s67 -o compressed/lena-s67.png lena.png
pngloss -fv -s68 -o compressed/lena-s68.png lena.png
pngloss -fv -s69 -o compressed/lena-s69.png lena.png
pngloss -fv -s70 -o compressed/lena-s70.png lena.png
pngloss -fv -s71 -o compressed/lena-s71.png lena.png
pngloss -fv -s72 -o compressed/lena-s72.png lena.png
pngloss -fv -s73 -o compressed/lena-s73.png lena.png
pngloss -fv -s74 -o compressed/lena-s74.png lena.png
pngloss -fv -s75 -o compressed/lena-s75.png lena.png
pngloss -fv -s76 -o compressed/lena-s76.png lena.png
pngloss -fv -s77 -o compressed/lena-s77.png lena.png
pngloss -fv -s78 -o compressed/lena-s78.png lena.png
pngloss -fv -s79 -o compressed/lena-s79.png lena.png
pngloss -fv -s80 -o compressed/lena-s80.png lena.png
pngloss -fv -s81 -o compressed/lena-s81.png lena.png
pngloss -fv -s82 -o compressed/lena-s82.png lena.png
pngloss -fv -s83 -o compressed/lena-s83.png lena.png
pngloss -fv -s84 -o compressed/lena-s84.png lena.png
pngloss -fv -s85 -o compressed/lena-s85.png lena.png
pngloss -fv -s86 -o compressed/lena-s86.png lena.png
pngloss -fv -s87 -o compressed/lena-s87.png lena.png
pngloss -fv -s88 -o compressed/lena-s88.png lena.png
pngloss -fv -s89 -o compressed/lena-s89.png lena.png
pngloss -fv -s90 -o compressed/lena-s90.png lena.png
pngloss -fv -s91 -o compressed/lena-s91.png lena.png
pngloss -fv -s92 -o compressed/lena-s92.png lena.png
pngloss -fv -s93 -o compressed/lena-s93.png lena.png
pngloss -fv -s94 -o compressed/lena-s94.png lena.png
pngloss -fv -s95 -o compressed/lena-s95.png lena.png
pngloss -fv -s96 -o compressed/lena-s96.png lena.png
pngloss -fv -s97 -o compressed/lena-s97.png lena.png
pngloss -fv -s98 -o compressed/lena-s98.png lena.png
pngloss -fv -s99 -o compressed/lena-s99.png lena.png
pngloss -fv -s1 -o compressed/parrots-s01.png parrots.png
pngloss -fv -s2 -o compressed/parrots-s02.png parrots.png
pngloss -fv -s3 -o compressed/parrots-s03.png parrots.png
pngloss -fv -s4 -o compressed/parrots-s04.png parrots.png
pngloss -fv -s5 -o compressed/parrots-s05.png parrots.png
pngloss -fv -s6 -o compressed/parrots-s06.png parrots.png
pngloss -fv -s7 -o compressed/parrots-s07.png parrots.png
pngloss -fv -s8 -o compressed/parrots-s08.png parrots.png
pngloss -fv -s9 -o compressed/parrots-s09.png parrots.png
pngloss -fv -s10 -o compressed/parrots-s10.png parrots.png
pngloss -fv -s11 -o compressed/parrots-s11.png parrots.png
pngloss -fv -s12 -o compressed/parrots-s12.png parrots.png
pngloss -fv -s13 -o compressed/parrots-s13.png parrots.png
pngloss -fv -s14 -o compressed/parrots-s14.png parrots.png
pngloss -fv -s15 -o compressed/parrots-s15.png parrots.png
pngloss -fv -s16 -o compressed/parrots-s16.png parrots.png
pngloss -fv -s17 -o compressed/parrots-s17.png parrots.png
pngloss -fv -s18 -o compressed/parrots-s18.png parrots.png
pngloss -fv -s19 -o compressed/parrots-s19.png parrots.png
pngloss -fv -s20 -o compressed/parrots-s20.png parrots.png
pngloss -fv -s21 -o compressed/parrots-s21.png parrots.png
pngloss -fv -s22 -o compressed/parrots-s22.png parrots.png
pngloss -fv -s23 -o compressed/parrots-s23.png parrots.png
pngloss -fv -s24 -o compressed/parrots-s24.png parrots.png
pngloss -fv -s25 -o compressed/parrots-s25.png parrots.png
pngloss -fv -s26 -o compressed/parrots-s26.png parrots.png
pngloss -fv -s27 -o compressed/parrots-s27.png parrots.png
pngloss -fv -s28 -o compressed/parrots-s28.png parrots.png
pngloss -fv -s29 -o compressed/parrots-s29.png parrots.png
pngloss -fv -s30 -o compressed/parrots-s30.png parrots.png
pngloss -fv -s31 -o compressed/parrots-s31.png parrots.png
pngloss -fv -s32 -o compressed/parrots-s32.png parrots.png
pngloss -fv -s33 -o compressed/parrots-s33.png parrots.png
pngloss -fv -s34 -o compressed/parrots-s34.png parrots.png
pngloss -fv -s35 -o compressed/parrots-s35.png parrots.png
pngloss -fv -s36 -o compressed/parrots-s36.png parrots.png
pngloss -fv -s37 -o compressed/parrots-s37.png parrots.png
pngloss -fv -s38 -o compressed/parrots-s38.png parrots.png
pngloss -fv -s39 -o compressed/parrots-s39.png parrots.png
pngloss -fv -s40 -o compressed/parrots-s40.png parrots.png
pngloss -fv -s41 -o compressed/parrots-s41.png parrots.png
pngloss -fv -s42 -o compressed/parrots-s42.png parrots.png
pngloss -fv -s43 -o compressed/parrots-s43.png parrots.png
pngloss -fv -s44 -o compressed/parrots-s44.png parrots.png
pngloss -fv -s45 -o compressed/parrots-s45.png parrots.png
pngloss -fv -s46 -o compressed/parrots-s46.png parrots.png
pngloss -fv -s47 -o compressed/parrots-s47.png parrots.png
pngloss -fv -s48 -o compressed/parrots-s48.png parrots.png
pngloss -fv -s49 -o compressed/parrots-s49.png parrots.png
pngloss -fv -s50 -o compressed/parrots-s50.png parrots.png
pngloss -fv -s51 -o compressed/parrots-s51.png parrots.png
pngloss -fv -s52 -o compressed/parrots-s52.png parrots.png
pngloss -fv -s53 -o compressed/parrots-s53.png parrots.png
pngloss -fv -s54 -o compressed/parrots-s54.png parrots.png
pngloss -fv -s55 -o compressed/parrots-s55.png parrots.png
pngloss -fv -s56 -o compressed/parrots-s56.png parrots.png
pngloss -fv -s57 -o compressed/parrots-s57.png parrots.png
pngloss -fv -s58 -o compressed/parrots-s58.png parrots.png
pngloss -fv -s59 -o compressed/parrots-s59.png parrots.png
pngloss -fv -s60 -o compressed/parrots-s60.png parrots.png
pngloss -fv -s61 -o compressed/parrots-s61.png parrots.png
pngloss -fv -s62 -o compressed/parrots-s62.png parrots.png
pngloss -fv -s63 -o compressed/parrots-s63.png parrots.png
pngloss -fv -s64 -o compressed/parrots-s64.png parrots.png
pngloss -fv -s65 -o compressed/parrots-s65.png parrots.png
pngloss -fv -s66 -o compressed/parrots-s66.png parrots.png
pngloss -fv -s67 -o compressed/parrots-s67.png parrots.png
pngloss -fv -s68 -o compressed/parrots-s68.png parrots.png
pngloss -fv -s69 -o compressed/parrots-s69.png parrots.png
pngloss -fv -s70 -o compressed/parrots-s70.png parrots.png
pngloss -fv -s71 -o compressed/parrots-s71.png parrots.png
pngloss -fv -s72 -o compressed/parrots-s72.png parrots.png
pngloss -fv -s73 -o compressed/parrots-s73.png parrots.png
pngloss -fv -s74 -o compressed/parrots-s74.png parrots.png
pngloss -fv -s75 -o compressed/parrots-s75.png parrots.png
pngloss -fv -s76 -o compressed/parrots-s76.png parrots.png
pngloss -fv -s77 -o compressed/parrots-s77.png parrots.png
pngloss -fv -s78 -o compressed/parrots-s78.png parrots.png
pngloss -fv -s79 -o compressed/parrots-s79.png parrots.png
pngloss -fv -s80 -o compressed/parrots-s80.png parrots.png
pngloss -fv -s81 -o compressed/parrots-s81.png parrots.png
pngloss -fv -s82 -o compressed/parrots-s82.png parrots.png
pngloss -fv -s83 -o compressed/parrots-s83.png parrots.png
pngloss -fv -s84 -o compressed/parrots-s84.png parrots.png
pngloss -fv -s85 -o compressed/parrots-s85.png parrots.png
pngloss -fv -s86 -o compressed/parrots-s86.png parrots.png
pngloss -fv -s87 -o compressed/parrots-s87.png parrots.png
pngloss -fv -s88 -o compressed/parrots-s88.png parrots.png
pngloss -fv -s89 -o compressed/parrots-s89.png parrots.png
pngloss -fv -s90 -o compressed/parrots-s90.png parrots.png
pngloss -fv -s91 -o compressed/parrots-s91.png parrots.png
pngloss -fv -s92 -o compressed/parrots-s92.png parrots.png
pngloss -fv -s93 -o compressed/parrots-s93.png parrots.png
pngloss -fv -s94 -o compressed/parrots-s94.png parrots.png
pngloss -fv -s95 -o compressed/parrots-s95.png parrots.png
pngloss -fv -s96 -o compressed/parrots-s96.png parrots.png
pngloss -fv -s97 -o compressed/parrots-s97.png parrots.png
pngloss -fv -s98 -o compressed/parrots-s98.png parrots.png
pngloss -fv -s99 -o compressed/parrots-s99.png parrots.png
pngloss -fv -s1 -o compressed/redbrush-s01.png redbrush.png
pngloss -fv -s2 -o compressed/redbrush-s02.png redbrush.png
pngloss -fv -s3 -o compressed/redbrush-s03.png redbrush.png
pngloss -fv -s4 -o compressed/redbrush-s04.png redbrush.png
pngloss -fv -s5 -o compressed/redbrush-s05.png redbrush.png
pngloss -fv -s6 -o compressed/redbrush-s06.png redbrush.png
pngloss -fv -s7 -o compressed/redbrush-s07.png redbrush.png
pngloss -fv -s8 -o compressed/redbrush-s08.png redbrush.png
pngloss -fv -s9 -o compressed/redbrush-s09.png redbrush.png
pngloss -fv -s10 -o compressed/redbrush-s10.png redbrush.png
pngloss -fv -s11 -o compressed/redbrush-s11.png redbrush.png
pngloss -fv -s12 -o compressed/redbrush-s12.png redbrush.png
pngloss -fv -s13 -o compressed/redbrush-s13.png redbrush.png
pngloss -fv -s14 -o compressed/redbrush-s14.png redbrush.png
pngloss -fv -s15 -o compressed/redbrush-s15.png redbrush.png
pngloss -fv -s16 -o compressed/redbrush-s16.png redbrush.png
pngloss -fv -s17 -o compressed/redbrush-s17.png redbrush.png
pngloss -fv -s18 -o compressed/redbrush-s18.png redbrush.png
pngloss -fv -s19 -o compressed/redbrush-s19.png redbrush.png
pngloss -fv -s20 -o compressed/redbrush-s20.png redbrush.png
pngloss -fv -s21 -o compressed/redbrush-s21.png redbrush.png
pngloss -fv -s22 -o compressed/redbrush-s22.png redbrush.png
pngloss -fv -s23 -o compressed/redbrush-s23.png redbrush.png
pngloss -fv -s24 -o compressed/redbrush-s24.png redbrush.png
pngloss -fv -s25 -o compressed/redbrush-s25.png redbrush.png
pngloss -fv -s26 -o compressed/redbrush-s26.png redbrush.png
pngloss -fv -s27 -o compressed/redbrush-s27.png redbrush.png
pngloss -fv -s28 -o compressed/redbrush-s28.png redbrush.png
pngloss -fv -s29 -o compressed/redbrush-s29.png redbrush.png
pngloss -fv -s30 -o compressed/redbrush-s30.png redbrush.png
pngloss -fv -s31 -o compressed/redbrush-s31.png redbrush.png
pngloss -fv -s32 -o compressed/redbrush-s32.png redbrush.png
pngloss -fv -s33 -o compressed/redbrush-s33.png redbrush.png
pngloss -fv -s34 -o compressed/redbrush-s34.png redbrush.png
pngloss -fv -s35 -o compressed/redbrush-s35.png redbrush.png
pngloss -fv -s36 -o compressed/redbrush-s36.png redbrush.png
pngloss -fv -s37 -o compressed/redbrush-s37.png redbrush.png
pngloss -fv -s38 -o compressed/redbrush-s38.png redbrush.png
pngloss -fv -s39 -o compressed/redbrush-s39.png redbrush.png
pngloss -fv -s40 -o compressed/redbrush-s40.png redbrush.png
pngloss -fv -s41 -o compressed/redbrush-s41.png redbrush.png
pngloss -fv -s42 -o compressed/redbrush-s42.png redbrush.png
pngloss -fv -s43 -o compressed/redbrush-s43.png redbrush.png
pngloss -fv -s44 -o compressed/redbrush-s44.png redbrush.png
pngloss -fv -s45 -o compressed/redbrush-s45.png redbrush.png
pngloss -fv -s46 -o compressed/redbrush-s46.png redbrush.png
pngloss -fv -s47 -o compressed/redbrush-s47.png redbrush.png
pngloss -fv -s48 -o compressed/redbrush-s48.png redbrush.png
pngloss -fv -s49 -o compressed/redbrush-s49.png redbrush.png
pngloss -fv -s50 -o compressed/redbrush-s50.png redbrush.png
pngloss -fv -s51 -o compressed/redbrush-s51.png redbrush.png
pngloss -fv -s52 -o compressed/redbrush-s52.png redbrush.png
pngloss -fv -s53 -o compressed/redbrush-s53.png redbrush.png
pngloss -fv -s54 -o compressed/redbrush-s54.png redbrush.png
pngloss -fv -s55 -o compressed/redbrush-s55.png redbrush.png
pngloss -fv -s56 -o compressed/redbrush-s56.png redbrush.png
pngloss -fv -s57 -o compressed/redbrush-s57.png redbrush.png
pngloss -fv -s58 -o compressed/redbrush-s58.png redbrush.png
pngloss -fv -s59 -o compressed/redbrush-s59.png redbrush.png
pngloss -fv -s60 -o compressed/redbrush-s60.png redbrush.png
pngloss -fv -s61 -o compressed/redbrush-s61.png redbrush.png
pngloss -fv -s62 -o compressed/redbrush-s62.png redbrush.png
pngloss -fv -s63 -o compressed/redbrush-s63.png redbrush.png
pngloss -fv -s64 -o compressed/redbrush-s64.png redbrush.png
pngloss -fv -s65 -o compressed/redbrush-s65.png redbrush.png
pngloss -fv -s66 -o compressed/redbrush-s66.png redbrush.png
pngloss -fv -s67 -o compressed/redbrush-s67.png redbrush.png
pngloss -fv -s68 -o compressed/redbrush-s68.png redbrush.png
pngloss -fv -s69 -o compressed/redbrush-s69.png redbrush.png
pngloss -fv -s70 -o compressed/redbrush-s70.png redbrush.png
pngloss -fv -s71 -o compressed/redbrush-s71.png redbrush.png
pngloss -fv -s72 -o compressed/redbrush-s72.png redbrush.png
pngloss -fv -s73 -o compressed/redbrush-s73.png redbrush.png
pngloss -fv -s74 -o compressed/redbrush-s74.png redbrush.png
pngloss -fv -s75 -o compressed/redbrush-s75.png redbrush.png
pngloss -fv -s76 -o compressed/redbrush-s76.png redbrush.png
pngloss -fv -s77 -o compressed/redbrush-s77.png redbrush.png
pngloss -fv -s78 -o compressed/redbrush-s78.png redbrush.png
pngloss -fv -s79 -o compressed/redbrush-s79.png redbrush.png
pngloss -fv -s80 -o compressed/redbrush-s80.png redbrush.png
pngloss -fv -s81 -o compressed/redbrush-s81.png redbrush.png
pngloss -fv -s82 -o compressed/redbrush-s82.png redbrush.png
pngloss -fv -s83 -o compressed/redbrush-s83.png redbrush.png
pngloss -fv -s84 -o compressed/redbrush-s84.png redbrush.png
pngloss -fv -s85 -o compressed/redbrush-s85.png redbrush.png
pngloss -fv -s86 -o compressed/redbrush-s86.png redbrush.png
pngloss -fv -s87 -o compressed/redbrush-s87.png redbrush.png
pngloss -fv -s88 -o compressed/redbrush-s88.png redbrush.png
pngloss -fv -s89 -o compressed/redbrush-s89.png redbrush.png
pngloss -fv -s90 -o compressed/redbrush-s90.png redbrush.png
pngloss -fv -s91 -o compressed/redbrush-s91.png redbrush.png
pngloss -fv -s92 -o compressed/redbrush-s92.png redbrush.png
pngloss -fv -s93 -o compressed/redbrush-s93.png redbrush.png
pngloss -fv -s94 -o compressed/redbrush-s94.png redbrush.png
pngloss -fv -s95 -o compressed/redbrush-s95.png redbrush.png
pngloss -fv -s96 -o compressed/redbrush-s96.png redbrush.png
pngloss -fv -s97 -o compressed/redbrush-s97.png redbrush.png
pngloss -fv -s98 -o compressed/redbrush-s98.png redbrush.png
pngloss -fv -s99 -o compressed/redbrush-s99.png redbrush.png
pngloss -fv -s1 -o compressed/rose-s01.png rose.png
pngloss -fv -s2 -o compressed/rose-s02.png rose.png
pngloss -fv -s3 -o compressed/rose-s03.png rose.png
pngloss -fv -s4 -o compressed/rose-s04.png rose.png
pngloss -fv -s5 -o compressed/rose-s05.png rose.png
pngloss -fv -s6 -o compressed/rose-s06.png rose.png
pngloss -fv -s7 -o compressed/rose-s07.png rose.png
pngloss -fv -s8 -o compressed/rose-s08.png rose.png
pngloss -fv -s9 -o compressed/rose-s09.png rose.png
pngloss -fv -s10 -o compressed/rose-s10.png rose.png
pngloss -fv -s11 -o compressed/rose-s11.png rose.png
pngloss -fv -s12 -o compressed/rose-s12.png rose.png
pngloss -fv -s13 -o compressed/rose-s13.png rose.png
pngloss -fv -s14 -o compressed/rose-s14.png rose.png
pngloss -fv -s15 -o compressed/rose-s15.png rose.png
pngloss -fv -s16 -o compressed/rose-s16.png rose.png
pngloss -fv -s17 -o compressed/rose-s17.png rose.png
pngloss -fv -s18 -o compressed/rose-s18.png rose.png
pngloss -fv -s19 -o compressed/rose-s19.png rose.png
pngloss -fv -s20 -o compressed/rose-s20.png rose.png
pngloss -fv -s21 -o compressed/rose-s21.png rose.png
pngloss -fv -s22 -o compressed/rose-s22.png rose.png
pngloss -fv -s23 -o compressed/rose-s23.png rose.png
pngloss -fv -s24 -o compressed/rose-s24.png rose.png
pngloss -fv -s25 -o compressed/rose-s25.png rose.png
pngloss -fv -s26 -o compressed/rose-s26.png rose.png
pngloss -fv -s27 -o compressed/rose-s27.png rose.png
pngloss -fv -s28 -o compressed/rose-s28.png rose.png
pngloss -fv -s29 -o compressed/rose-s29.png rose.png
pngloss -fv -s30 -o compressed/rose-s30.png rose.png
pngloss -fv -s31 -o compressed/rose-s31.png rose.png
pngloss -fv -s32 -o compressed/rose-s32.png rose.png
pngloss -fv -s33 -o compressed/rose-s33.png rose.png
pngloss -fv -s34 -o compressed/rose-s34.png rose.png
pngloss -fv -s35 -o compressed/rose-s35.png rose.png
pngloss -fv -s36 -o compressed/rose-s36.png rose.png
pngloss -fv -s37 -o compressed/rose-s37.png rose.png
pngloss -fv -s38 -o compressed/rose-s38.png rose.png
pngloss -fv -s39 -o compressed/rose-s39.png rose.png
pngloss -fv -s40 -o compressed/rose-s40.png rose.png
pngloss -fv -s41 -o compressed/rose-s41.png rose.png
pngloss -fv -s42 -o compressed/rose-s42.png rose.png
pngloss -fv -s43 -o compressed/rose-s43.png rose.png
pngloss -fv -s44 -o compressed/rose-s44.png rose.png
pngloss -fv -s45 -o compressed/rose-s45.png rose.png
pngloss -fv -s46 -o compressed/rose-s46.png rose.png
pngloss -fv -s47 -o compressed/rose-s47.png rose.png
pngloss -fv -s48 -o compressed/rose-s48.png rose.png
pngloss -fv -s49 -o compressed/rose-s49.png rose.png
pngloss -fv -s50 -o compressed/rose-s50.png rose.png
pngloss -fv -s51 -o compressed/rose-s51.png rose.png
pngloss -fv -s52 -o compressed/rose-s52.png rose.png
pngloss -fv -s53 -o compressed/rose-s53.png rose.png
pngloss -fv -s54 -o compressed/rose-s54.png rose.png
pngloss -fv -s55 -o compressed/rose-s55.png rose.png
pngloss -fv -s56 -o compressed/rose-s56.png rose.png
pngloss -fv -s57 -o compressed/rose-s57.png rose.png
pngloss -fv -s58 -o compressed/rose-s58.png rose.png
pngloss -fv -s59 -o compressed/rose-s59.png rose.png
pngloss -fv -s60 -o compressed/rose-s60.png rose.png
pngloss -fv -s61 -o compressed/rose-s61.png rose.png
pngloss -fv -s62 -o compressed/rose-s62.png rose.png
pngloss -fv -s63 -o compressed/rose-s63.png rose.png
pngloss -fv -s64 -o compressed/rose-s64.png rose.png
pngloss -fv -s65 -o compressed/rose-s65.png rose.png
pngloss -fv -s66 -o compressed/rose-s66.png rose.png
pngloss -fv -s67 -o compressed/rose-s67.png rose.png
pngloss -fv -s68 -o compressed/rose-s68.png rose.png
pngloss -fv -s69 -o compressed/rose-s69.png rose.png
pngloss -fv -s70 -o compressed/rose-s70.png rose.png
pngloss -fv -s71 -o compressed/rose-s71.png rose.png
pngloss -fv -s72 -o compressed/rose-s72.png rose.png
pngloss -fv -s73 -o compressed/rose-s73.png rose.png
pngloss -fv -s74 -o compressed/rose-s74.png rose.png
pngloss -fv -s75 -o compressed/rose-s75.png rose.png
pngloss -fv -s76 -o compressed/rose-s76.png rose.png
pngloss -fv -s77 -o compressed/rose-s77.png rose.png
pngloss -fv -s78 -o compressed/rose-s78.png rose.png
pngloss -fv -s79 -o compressed/rose-s79.png rose.png
pngloss -fv -s80 -o compressed/rose-s80.png rose.png
pngloss -fv -s81 -o compressed/rose-s81.png rose.png
pngloss -fv -s82 -o compressed/rose-s82.png rose.png
pngloss -fv -s83 -o compressed/rose-s83.png rose.png
pngloss -fv -s84 -o compressed/rose-s84.png rose.png
pngloss -fv -s85 -o compressed/rose-s85.png rose.png
pngloss -fv -s86 -o compressed/rose-s86.png rose.png
pngloss -fv -s87 -o compressed/rose-s87.png rose.png
pngloss -fv -s88 -o compressed/rose-s88.png rose.png
pngloss -fv -s89 -o compressed/rose-s89.png rose.png
pngloss -fv -s90 -o compressed/rose-s90.png rose.png
pngloss -fv -s91 -o compressed/rose-s91.png rose.png
pngloss -fv -s92 -o compressed/rose-s92.png rose.png
pngloss -fv -s93 -o compressed/rose-s93.png rose.png
pngloss -fv -s94 -o compressed/rose-s94.png rose.png
pngloss -fv -s95 -o compressed/rose-s95.png rose.png
pngloss -fv -s96 -o compressed/rose-s96.png rose.png
pngloss -fv -s97 -o compressed/rose-s97.png rose.png
pngloss -fv -s98 -o compressed/rose-s98.png rose.png
pngloss -fv -s99 -o compressed/rose-s99.png rose.png
pngloss -fv -s1 -o compressed/ssr-s01.png ssr.png
pngloss -fv -s2 -o compressed/ssr-s02.png ssr.png
pngloss -fv -s3 -o compressed/ssr-s03.png ssr.png
pngloss -fv -s4 -o compressed/ssr-s04.png ssr.png
pngloss -fv -s5 -o compressed/ssr-s05.png ssr.png
pngloss -fv -s6 -o compressed/ssr-s06.png ssr.png
pngloss -fv -s7 -o compressed/ssr-s07.png ssr.png
pngloss -fv -s8 -o compressed/ssr-s08.png ssr.png
pngloss -fv -s9 -o compressed/ssr-s09.png ssr.png
pngloss -fv -s10 -o compressed/ssr-s10.png ssr.png
pngloss -fv -s11 -o compressed/ssr-s11.png ssr.png
pngloss -fv -s12 -o compressed/ssr-s12.png ssr.png
pngloss -fv -s13 -o compressed/ssr-s13.png ssr.png
pngloss -fv -s14 -o compressed/ssr-s14.png ssr.png
pngloss -fv -s15 -o compressed/ssr-s15.png ssr.png
pngloss -fv -s16 -o compressed/ssr-s16.png ssr.png
pngloss -fv -s17 -o compressed/ssr-s17.png ssr.png
pngloss -fv -s18 -o compressed/ssr-s18.png ssr.png
pngloss -fv -s19 -o compressed/ssr-s19.png ssr.png
pngloss -fv -s20 -o compressed/ssr-s20.png ssr.png
pngloss -fv -s21 -o compressed/ssr-s21.png ssr.png
pngloss -fv -s22 -o compressed/ssr-s22.png ssr.png
pngloss -fv -s23 -o compressed/ssr-s23.png ssr.png
pngloss -fv -s24 -o compressed/ssr-s24.png ssr.png
pngloss -fv -s25 -o compressed/ssr-s25.png ssr.png
pngloss -fv -s26 -o compressed/ssr-s26.png ssr.png
pngloss -fv -s27 -o compressed/ssr-s27.png ssr.png
pngloss -fv -s28 -o compressed/ssr-s28.png ssr.png
pngloss -fv -s29 -o compressed/ssr-s29.png ssr.png
pngloss -fv -s30 -o compressed/ssr-s30.png ssr.png
pngloss -fv -s31 -o compressed/ssr-s31.png ssr.png
pngloss -fv -s32 -o compressed/ssr-s32.png ssr.png
pngloss -fv -s33 -o compressed/ssr-s33.png ssr.png
pngloss -fv -s34 -o compressed/ssr-s34.png ssr.png
pngloss -fv -s35 -o compressed/ssr-s35.png ssr.png
pngloss -fv -s36 -o compressed/ssr-s36.png ssr.png
pngloss -fv -s37 -o compressed/ssr-s37.png ssr.png
pngloss -fv -s38 -o compressed/ssr-s38.png ssr.png
pngloss -fv -s39 -o compressed/ssr-s39.png ssr.png
pngloss -fv -s40 -o compressed/ssr-s40.png ssr.png
pngloss -fv -s41 -o compressed/ssr-s41.png ssr.png
pngloss -fv -s42 -o compressed/ssr-s42.png ssr.png
pngloss -fv -s43 -o compressed/ssr-s43.png ssr.png
pngloss -fv -s44 -o compressed/ssr-s44.png ssr.png
pngloss -fv -s45 -o compressed/ssr-s45.png ssr.png
pngloss -fv -s46 -o compressed/ssr-s46.png ssr.png
pngloss -fv -s47 -o compressed/ssr-s47.png ssr.png
pngloss -fv -s48 -o compressed/ssr-s48.png ssr.png
pngloss -fv -s49 -o compressed/ssr-s49.png ssr.png
pngloss -fv -s50 -o compressed/ssr-s50.png ssr.png
pngloss -fv -s51 -o compressed/ssr-s51.png ssr.png
pngloss -fv -s52 -o compressed/ssr-s52.png ssr.png
pngloss -fv -s53 -o compressed/ssr-s53.png ssr.png
pngloss -fv -s54 -o compressed/ssr-s54.png ssr.png
pngloss -fv -s55 -o compressed/ssr-s55.png ssr.png
pngloss -fv -s56 -o compressed/ssr-s56.png ssr.png
pngloss -fv -s57 -o compressed/ssr-s57.png ssr.png
pngloss -fv -s58 -o compressed/ssr-s58.png ssr.png
pngloss -fv -s59 -o compressed/ssr-s59.png ssr.png
pngloss -fv -s60 -o compressed/ssr-s60.png ssr.png
pngloss -fv -s61 -o compressed/ssr-s61.png ssr.png
pngloss -fv -s62 -o compressed/ssr-s62.png ssr.png
pngloss -fv -s63 -o compressed/ssr-s63.png ssr.png
pngloss -fv -s64 -o compressed/ssr-s64.png ssr.png
pngloss -fv -s65 -o compressed/ssr-s65.png ssr.png
pngloss -fv -s66 -o compressed/ssr-s66.png ssr.png
pngloss -fv -s67 -o compressed/ssr-s67.png ssr.png
pngloss -fv -s68 -o compressed/ssr-s68.png ssr.png
pngloss -fv -s69 -o compressed/ssr-s69.png ssr.png
pngloss -fv -s70 -o compressed/ssr-s70.png ssr.png
pngloss -fv -s71 -o compressed/ssr-s71.png ssr.png
pngloss -fv -s72 -o compressed/ssr-s72.png ssr.png
pngloss -fv -s73 -o compressed/ssr-s73.png ssr.png
pngloss -fv -s74 -o compressed/ssr-s74.png ssr.png
pngloss -fv -s75 -o compressed/ssr-s75.png ssr.png
pngloss -fv -s76 -o compressed/ssr-s76.png ssr.png
pngloss -fv -s77 -o compressed/ssr-s77.png ssr.png
pngloss -fv -s78 -o compressed/ssr-s78.png ssr.png
pngloss -fv -s79 -o compressed/ssr-s79.png ssr.png
pngloss -fv -s80 -o compressed/ssr-s80.png ssr.png
pngloss -fv -s81 -o compressed/ssr-s81.png ssr.png
pngloss -fv -s82 -o compressed/ssr-s82.png ssr.png
pngloss -fv -s83 -o compressed/ssr-s83.png ssr.png
pngloss -fv -s84 -o compressed/ssr-s84.png ssr.png
pngloss -fv -s85 -o compressed/ssr-s85.png ssr.png
pngloss -fv -s86 -o compressed/ssr-s86.png ssr.png
pngloss -fv -s87 -o compressed/ssr-s87.png ssr.png
pngloss -fv -s88 -o compressed/ssr-s88.png ssr.png
pngloss -fv -s89 -o compressed/ssr-s89.png ssr.png
pngloss -fv -s90 -o compressed/ssr-s90.png ssr.png
pngloss -fv -s91 -o compressed/ssr-s91.png ssr.png
pngloss -fv -s92 -o compressed/ssr-s92.png ssr.png
pngloss -fv -s93 -o compressed/ssr-s93.png ssr.png
pngloss -fv -s94 -o compressed/ssr-s94.png ssr.png
pngloss -fv -s95 -o compressed/ssr-s95.png ssr.png
pngloss -fv -s96 -o compressed/ssr-s96.png ssr.png
pngloss -fv -s97 -o compressed/ssr-s97.png ssr.png
pngloss -fv -s98 -o compressed/ssr-s98.png ssr.png
pngloss -fv -s99 -o compressed/ssr-s99.png ssr.png
pngloss -fv -s1 -o compressed/tenko-s01.png tenko.png
pngloss -fv -s2 -o compressed/tenko-s02.png tenko.png
pngloss -fv -s3 -o compressed/tenko-s03.png tenko.png
pngloss -fv -s4 -o compressed/tenko-s04.png tenko.png
pngloss -fv -s5 -o compressed/tenko-s05.png tenko.png
pngloss -fv -s6 -o compressed/tenko-s06.png tenko.png
pngloss -fv -s7 -o compressed/tenko-s07.png tenko.png
pngloss -fv -s8 -o compressed/tenko-s08.png tenko.png
pngloss -fv -s9 -o compressed/tenko-s09.png tenko.png
pngloss -fv -s10 -o compressed/tenko-s10.png tenko.png
pngloss -fv -s11 -o compressed/tenko-s11.png tenko.png
pngloss -fv -s12 -o compressed/tenko-s12.png tenko.png
pngloss -fv -s13 -o compressed/tenko-s13.png tenko.png
pngloss -fv -s14 -o compressed/tenko-s14.png tenko.png
pngloss -fv -s15 -o compressed/tenko-s15.png tenko.png
pngloss -fv -s16 -o compressed/tenko-s16.png tenko.png
pngloss -fv -s17 -o compressed/tenko-s17.png tenko.png
pngloss -fv -s18 -o compressed/tenko-s18.png tenko.png
pngloss -fv -s19 -o compressed/tenko-s19.png tenko.png
pngloss -fv -s20 -o compressed/tenko-s20.png tenko.png
pngloss -fv -s21 -o compressed/tenko-s21.png tenko.png
pngloss -fv -s22 -o compressed/tenko-s22.png tenko.png
pngloss -fv -s23 -o compressed/tenko-s23.png tenko.png
pngloss -fv -s24 -o compressed/tenko-s24.png tenko.png
pngloss -fv -s25 -o compressed/tenko-s25.png tenko.png
pngloss -fv -s26 -o compressed/tenko-s26.png tenko.png
pngloss -fv -s27 -o compressed/tenko-s27.png tenko.png
pngloss -fv -s28 -o compressed/tenko-s28.png tenko.png
pngloss -fv -s29 -o compressed/tenko-s29.png tenko.png
pngloss -fv -s30 -o compressed/tenko-s30.png tenko.png
pngloss -fv -s31 -o compressed/tenko-s31.png tenko.png
pngloss -fv -s32 -o compressed/tenko-s32.png tenko.png
pngloss -fv -s33 -o compressed/tenko-s33.png tenko.png
pngloss -fv -s34 -o compressed/tenko-s34.png tenko.png
pngloss -fv -s35 -o compressed/tenko-s35.png tenko.png
pngloss -fv -s36 -o compressed/tenko-s36.png tenko.png
pngloss -fv -s37 -o compressed/tenko-s37.png tenko.png
pngloss -fv -s38 -o compressed/tenko-s38.png tenko.png
pngloss -fv -s39 -o compressed/tenko-s39.png tenko.png
pngloss -fv -s40 -o compressed/tenko-s40.png tenko.png
pngloss -fv -s41 -o compressed/tenko-s41.png tenko.png
pngloss -fv -s42 -o compressed/tenko-s42.png tenko.png
pngloss -fv -s43 -o compressed/tenko-s43.png tenko.png
pngloss -fv -s44 -o compressed/tenko-s44.png tenko.png
pngloss -fv -s45 -o compressed/tenko-s45.png tenko.png
pngloss -fv -s46 -o compressed/tenko-s46.png tenko.png
pngloss -fv -s47 -o compressed/tenko-s47.png tenko.png
pngloss -fv -s48 -o compressed/tenko-s48.png tenko.png
pngloss -fv -s49 -o compressed/tenko-s49.png tenko.png
pngloss -fv -s50 -o compressed/tenko-s50.png tenko.png
pngloss -fv -s51 -o compressed/tenko-s51.png tenko.png
pngloss -fv -s52 -o compressed/tenko-s52.png tenko.png
pngloss -fv -s53 -o compressed/tenko-s53.png tenko.png
pngloss -fv -s54 -o compressed/tenko-s54.png tenko.png
pngloss -fv -s55 -o compressed/tenko-s55.png tenko.png
pngloss -fv -s56 -o compressed/tenko-s56.png tenko.png
pngloss -fv -s57 -o compressed/tenko-s57.png tenko.png
pngloss -fv -s58 -o compressed/tenko-s58.png tenko.png
pngloss -fv -s59 -o compressed/tenko-s59.png tenko.png
pngloss -fv -s60 -o compressed/tenko-s60.png tenko.png
pngloss -fv -s61 -o compressed/tenko-s61.png tenko.png
pngloss -fv -s62 -o compressed/tenko-s62.png tenko.png
pngloss -fv -s63 -o compressed/tenko-s63.png tenko.png
pngloss -fv -s64 -o compressed/tenko-s64.png tenko.png
pngloss -fv -s65 -o compressed/tenko-s65.png tenko.png
pngloss -fv -s66 -o compressed/tenko-s66.png tenko.png
pngloss -fv -s67 -o compressed/tenko-s67.png tenko.png
pngloss -fv -s68 -o compressed/tenko-s68.png tenko.png
pngloss -fv -s69 -o compressed/tenko-s69.png tenko.png
pngloss -fv -s70 -o compressed/tenko-s70.png tenko.png
pngloss -fv -s71 -o compressed/tenko-s71.png tenko.png
pngloss -fv -s72 -o compressed/tenko-s72.png tenko.png
pngloss -fv -s73 -o compressed/tenko-s73.png tenko.png
pngloss -fv -s74 -o compressed/tenko-s74.png tenko.png
pngloss -fv -s75 -o compressed/tenko-s75.png tenko.png
pngloss -fv -s76 -o compressed/tenko-s76.png tenko.png
pngloss -fv -s77 -o compressed/tenko-s77.png tenko.png
pngloss -fv -s78 -o compressed/tenko-s78.png tenko.png
pngloss -fv -s79 -o compressed/tenko-s79.png tenko.png
pngloss -fv -s80 -o compressed/tenko-s80.png tenko.png
pngloss -fv -s81 -o compressed/tenko-s81.png tenko.png
pngloss -fv -s82 -o compressed/tenko-s82.png tenko.png
pngloss -fv -s83 -o compressed/tenko-s83.png tenko.png
pngloss -fv -s84 -o compressed/tenko-s84.png tenko.png
pngloss -fv -s85 -o compressed/tenko-s85.png tenko.png
pngloss -fv -s86 -o compressed/tenko-s86.png tenko.png
pngloss -fv -s87 -o compressed/tenko-s87.png tenko.png
pngloss -fv -s88 -o compressed/tenko-s88.png tenko.png
pngloss -fv -s89 -o compressed/tenko-s89.png tenko.png
pngloss -fv -s90 -o compressed/tenko-s90.png tenko.png
pngloss -fv -s91 -o compressed/tenko-s91.png tenko.png
pngloss -fv -s92 -o compressed/tenko-s92.png tenko.png
pngloss -fv -s93 -o compressed/tenko-s93.png tenko.png
pngloss -fv -s94 -o compressed/tenko-s94.png tenko.png
pngloss -fv -s95 -o compressed/tenko-s95.png tenko.png
pngloss -fv -s96 -o compressed/tenko-s96.png tenko.png
pngloss -fv -s97 -o compressed/tenko-s97.png tenko.png
pngloss -fv -s98 -o compressed/tenko-s98.png tenko.png
pngloss -fv -s99 -o compressed/tenko-s99.png tenko.png
pngloss -fv -s1 -o compressed/tux-s01.png tux.png
pngloss -fv -s2 -o compressed/tux-s02.png tux.png
pngloss -fv -s3 -o compressed/tux-s03.png tux.png
pngloss -fv -s4 -o compressed/tux-s04.png tux.png
pngloss -fv -s5 -o compressed/tux-s05.png tux.png
pngloss -fv -s6 -o compressed/tux-s06.png tux.png
pngloss -fv -s7 -o compressed/tux-s07.png tux.png
pngloss -fv -s8 -o compressed/tux-s08.png tux.png
pngloss -fv -s9 -o compressed/tux-s09.png tux.png
pngloss -fv -s10 -o compressed/tux-s10.png tux.png
pngloss -fv -s11 -o compressed/tux-s11.png tux.png
pngloss -fv -s12 -o compressed/tux-s12.png tux.png
pngloss -fv -s13 -o compressed/tux-s13.png tux.png
pngloss -fv -s14 -o compressed/tux-s14.png tux.png
pngloss -fv -s15 -o compressed/tux-s15.png tux.png
pngloss -fv -s16 -o compressed/tux-s16.png tux.png
pngloss -fv -s17 -o compressed/tux-s17.png tux.png
pngloss -fv -s18 -o compressed/tux-s18.png tux.png
pngloss -fv -s19 -o compressed/tux-s19.png tux.png
pngloss -fv -s20 -o compressed/tux-s20.png tux.png
pngloss -fv -s21 -o compressed/tux-s21.png tux.png
pngloss -fv -s22 -o compressed/tux-s22.png tux.png
pngloss -fv -s23 -o compressed/tux-s23.png tux.png
pngloss -fv -s24 -o compressed/tux-s24.png tux.png
pngloss -fv -s25 -o compressed/tux-s25.png tux.png
pngloss -fv -s26 -o compressed/tux-s26.png tux.png
pngloss -fv -s27 -o compressed/tux-s27.png tux.png
pngloss -fv -s28 -o compressed/tux-s28.png tux.png
pngloss -fv -s29 -o compressed/tux-s29.png tux.png
pngloss -fv -s30 -o compressed/tux-s30.png tux.png
pngloss -fv -s31 -o compressed/tux-s31.png tux.png
pngloss -fv -s32 -o compressed/tux-s32.png tux.png
pngloss -fv -s33 -o compressed/tux-s33.png tux.png
pngloss -fv -s34 -o compressed/tux-s34.png tux.png
pngloss -fv -s35 -o compressed/tux-s35.png tux.png
pngloss -fv -s36 -o compressed/tux-s36.png tux.png
pngloss -fv -s37 -o compressed/tux-s37.png tux.png
pngloss -fv -s38 -o compressed/tux-s38.png tux.png
pngloss -fv -s39 -o compressed/tux-s39.png tux.png
pngloss -fv -s40 -o compressed/tux-s40.png tux.png
pngloss -fv -s41 -o compressed/tux-s41.png tux.png
pngloss -fv -s42 -o compressed/tux-s42.png tux.png
pngloss -fv -s43 -o compressed/tux-s43.png tux.png
pngloss -fv -s44 -o compressed/tux-s44.png tux.png
pngloss -fv -s45 -o compressed/tux-s45.png tux.png
pngloss -fv -s46 -o compressed/tux-s46.png tux.png
pngloss -fv -s47 -o compressed/tux-s47.png tux.png
pngloss -fv -s48 -o compressed/tux-s48.png tux.png
pngloss -fv -s49 -o compressed/tux-s49.png tux.png
pngloss -fv -s50 -o compressed/tux-s50.png tux.png
pngloss -fv -s51 -o compressed/tux-s51.png tux.png
pngloss -fv -s52 -o compressed/tux-s52.png tux.png
pngloss -fv -s53 -o compressed/tux-s53.png tux.png
pngloss -fv -s54 -o compressed/tux-s54.png tux.png
pngloss -fv -s55 -o compressed/tux-s55.png tux.png
pngloss -fv -s56 -o compressed/tux-s56.png tux.png
pngloss -fv -s57 -o compressed/tux-s57.png tux.png
pngloss -fv -s58 -o compressed/tux-s58.png tux.png
pngloss -fv -s59 -o compressed/tux-s59.png tux.png
pngloss -fv -s60 -o compressed/tux-s60.png tux.png
pngloss -fv -s61 -o compressed/tux-s61.png tux.png
pngloss -fv -s62 -o compressed/tux-s62.png tux.png
pngloss -fv -s63 -o compressed/tux-s63.png tux.png
pngloss -fv -s64 -o compressed/tux-s64.png tux.png
pngloss -fv -s65 -o compressed/tux-s65.png tux.png
pngloss -fv -s66 -o compressed/tux-s66.png tux.png
pngloss -fv -s67 -o compressed/tux-s67.png tux.png
pngloss -fv -s68 -o compressed/tux-s68.png tux.png
pngloss -fv -s69 -o compressed/tux-s69.png tux.png
pngloss -fv -s70 -o compressed/tux-s70.png tux.png
pngloss -fv -s71 -o compressed/tux-s71.png tux.png
pngloss -fv -s72 -o compressed/tux-s72.png tux.png
pngloss -fv -s73 -o compressed/tux-s73.png tux.png
pngloss -fv -s74 -o compressed/tux-s74.png tux.png
pngloss -fv -s75 -o compressed/tux-s75.png tux.png
pngloss -fv -s76 -o compressed/tux-s76.png tux.png
pngloss -fv -s77 -o compressed/tux-s77.png tux.png
pngloss -fv -s78 -o compressed/tux-s78.png tux.png
pngloss -fv -s79 -o compressed/tux-s79.png tux.png
pngloss -fv -s80 -o compressed/tux-s80.png tux.png
pngloss -fv -s81 -o compressed/tux-s81.png tux.png
pngloss -fv -s82 -o compressed/tux-s82.png tux.png
pngloss -fv -s83 -o compressed/tux-s83.png tux.png
pngloss -fv -s84 -o compressed/tux-s84.png tux.png
pngloss -fv -s85 -o compressed/tux-s85.png tux.png
pngloss -fv -s86 -o compressed/tux-s86.png tux.png
pngloss -fv -s87 -o compressed/tux-s87.png tux.png
pngloss -fv -s88 -o compressed/tux-s88.png tux.png
pngloss -fv -s89 -o compressed/tux-s89.png tux.png
pngloss -fv -s90 -o compressed/tux-s90.png tux.png
pngloss -fv -s91 -o compressed/tux-s91.png tux.png
pngloss -fv -s92 -o compressed/tux-s92.png tux.png
pngloss -fv -s93 -o compressed/tux-s93.png tux.png
pngloss -fv -s94 -o compressed/tux-s94.png tux.png
pngloss -fv -s95 -o compressed/tux-s95.png tux.png
pngloss -fv -s96 -o compressed/tux-s96.png tux.png
pngloss -fv -s97 -o compressed/tux-s97.png tux.png
pngloss -fv -s98 -o compressed/tux-s98.png tux.png
pngloss -fv -s99 -o compressed/tux-s99.png tux.png
