#!/bin/sh
pngloss -fv -s10 -o compressed/barbara-s10.png barbara.png
pngloss -fv -s20 -o compressed/barbara-s20.png barbara.png
pngloss -fv -s30 -o compressed/barbara-s30.png barbara.png
pngloss -fv -s40 -o compressed/barbara-s40.png barbara.png
pngloss -fv -s50 -o compressed/barbara-s50.png barbara.png
pngloss -fv -s60 -o compressed/barbara-s60.png barbara.png
pngloss -fv -s70 -o compressed/barbara-s70.png barbara.png
pngloss -fv -s80 -o compressed/barbara-s80.png barbara.png
pngloss -fv -s90 -o compressed/barbara-s90.png barbara.png
pngloss -fv -s10 -o compressed/david-s10.png david.png
pngloss -fv -s20 -o compressed/david-s20.png david.png
pngloss -fv -s30 -o compressed/david-s30.png david.png
pngloss -fv -s40 -o compressed/david-s40.png david.png
pngloss -fv -s50 -o compressed/david-s50.png david.png
pngloss -fv -s60 -o compressed/david-s60.png david.png
pngloss -fv -s70 -o compressed/david-s70.png david.png
pngloss -fv -s80 -o compressed/david-s80.png david.png
pngloss -fv -s90 -o compressed/david-s90.png david.png
pngloss -fv -s10 -o compressed/dice-s10.png dice.png
pngloss -fv -s20 -o compressed/dice-s20.png dice.png
pngloss -fv -s30 -o compressed/dice-s30.png dice.png
pngloss -fv -s40 -o compressed/dice-s40.png dice.png
pngloss -fv -s50 -o compressed/dice-s50.png dice.png
pngloss -fv -s60 -o compressed/dice-s60.png dice.png
pngloss -fv -s70 -o compressed/dice-s70.png dice.png
pngloss -fv -s80 -o compressed/dice-s80.png dice.png
pngloss -fv -s90 -o compressed/dice-s90.png dice.png
pngloss -fv -s10 -o compressed/girl-s10.png girl.png
pngloss -fv -s20 -o compressed/girl-s20.png girl.png
pngloss -fv -s30 -o compressed/girl-s30.png girl.png
pngloss -fv -s40 -o compressed/girl-s40.png girl.png
pngloss -fv -s50 -o compressed/girl-s50.png girl.png
pngloss -fv -s60 -o compressed/girl-s60.png girl.png
pngloss -fv -s70 -o compressed/girl-s70.png girl.png
pngloss -fv -s80 -o compressed/girl-s80.png girl.png
pngloss -fv -s90 -o compressed/girl-s90.png girl.png
pngloss -fv -s10 -o compressed/lena-s10.png lena.png
pngloss -fv -s20 -o compressed/lena-s20.png lena.png
pngloss -fv -s30 -o compressed/lena-s30.png lena.png
pngloss -fv -s40 -o compressed/lena-s40.png lena.png
pngloss -fv -s50 -o compressed/lena-s50.png lena.png
pngloss -fv -s60 -o compressed/lena-s60.png lena.png
pngloss -fv -s70 -o compressed/lena-s70.png lena.png
pngloss -fv -s80 -o compressed/lena-s80.png lena.png
pngloss -fv -s90 -o compressed/lena-s90.png lena.png
pngloss -fv -s10 -o compressed/parrots-s10.png parrots.png
pngloss -fv -s20 -o compressed/parrots-s20.png parrots.png
pngloss -fv -s30 -o compressed/parrots-s30.png parrots.png
pngloss -fv -s40 -o compressed/parrots-s40.png parrots.png
pngloss -fv -s50 -o compressed/parrots-s50.png parrots.png
pngloss -fv -s60 -o compressed/parrots-s60.png parrots.png
pngloss -fv -s70 -o compressed/parrots-s70.png parrots.png
pngloss -fv -s80 -o compressed/parrots-s80.png parrots.png
pngloss -fv -s90 -o compressed/parrots-s90.png parrots.png
pngloss -fv -s10 -o compressed/redbrush-s10.png redbrush.png
pngloss -fv -s20 -o compressed/redbrush-s20.png redbrush.png
pngloss -fv -s30 -o compressed/redbrush-s30.png redbrush.png
pngloss -fv -s40 -o compressed/redbrush-s40.png redbrush.png
pngloss -fv -s50 -o compressed/redbrush-s50.png redbrush.png
pngloss -fv -s60 -o compressed/redbrush-s60.png redbrush.png
pngloss -fv -s70 -o compressed/redbrush-s70.png redbrush.png
pngloss -fv -s80 -o compressed/redbrush-s80.png redbrush.png
pngloss -fv -s90 -o compressed/redbrush-s90.png redbrush.png
pngloss -fv -s10 -o compressed/rose-s10.png rose.png
pngloss -fv -s20 -o compressed/rose-s20.png rose.png
pngloss -fv -s30 -o compressed/rose-s30.png rose.png
pngloss -fv -s40 -o compressed/rose-s40.png rose.png
pngloss -fv -s50 -o compressed/rose-s50.png rose.png
pngloss -fv -s60 -o compressed/rose-s60.png rose.png
pngloss -fv -s70 -o compressed/rose-s70.png rose.png
pngloss -fv -s80 -o compressed/rose-s80.png rose.png
pngloss -fv -s90 -o compressed/rose-s90.png rose.png
pngloss -fv -s10 -o compressed/ssr-s10.png ssr.png
pngloss -fv -s20 -o compressed/ssr-s20.png ssr.png
pngloss -fv -s30 -o compressed/ssr-s30.png ssr.png
pngloss -fv -s40 -o compressed/ssr-s40.png ssr.png
pngloss -fv -s50 -o compressed/ssr-s50.png ssr.png
pngloss -fv -s60 -o compressed/ssr-s60.png ssr.png
pngloss -fv -s70 -o compressed/ssr-s70.png ssr.png
pngloss -fv -s80 -o compressed/ssr-s80.png ssr.png
pngloss -fv -s90 -o compressed/ssr-s90.png ssr.png
pngloss -fv -s10 -o compressed/tenko-s10.png tenko.png
pngloss -fv -s20 -o compressed/tenko-s20.png tenko.png
pngloss -fv -s30 -o compressed/tenko-s30.png tenko.png
pngloss -fv -s40 -o compressed/tenko-s40.png tenko.png
pngloss -fv -s50 -o compressed/tenko-s50.png tenko.png
pngloss -fv -s60 -o compressed/tenko-s60.png tenko.png
pngloss -fv -s70 -o compressed/tenko-s70.png tenko.png
pngloss -fv -s80 -o compressed/tenko-s80.png tenko.png
pngloss -fv -s90 -o compressed/tenko-s90.png tenko.png
pngloss -fv -s10 -o compressed/tux-s10.png tux.png
pngloss -fv -s20 -o compressed/tux-s20.png tux.png
pngloss -fv -s30 -o compressed/tux-s30.png tux.png
pngloss -fv -s40 -o compressed/tux-s40.png tux.png
pngloss -fv -s50 -o compressed/tux-s50.png tux.png
pngloss -fv -s60 -o compressed/tux-s60.png tux.png
pngloss -fv -s70 -o compressed/tux-s70.png tux.png
pngloss -fv -s80 -o compressed/tux-s80.png tux.png
pngloss -fv -s90 -o compressed/tux-s90.png tux.png
